
import { LoaderItem } from './types';

export const LOADERS: LoaderItem[] = [
  { id: '1', name: 'Classic Spinner', variant: 'classic-spinner', description: 'Rotating border ring.', category: 'spinners' },
  { id: '2', name: 'Square Spin', variant: 'square-spin', description: '3D-flipping square.', category: 'spinners' },
  { id: '3', name: 'Circular Dash', variant: 'circular-progress', description: 'SVG arc animation.', category: 'spinners' },
  { id: '4', name: 'Hex Spin', variant: 'hex-spin', description: 'Rotating hexagon.', category: 'spinners' },
  { id: '5', name: 'Fading Ring', variant: 'fading-ring', description: 'Opacity-cycling ring.', category: 'spinners' },
  { id: '6', name: 'Bouncing Dots', variant: 'dots-pulse', description: 'Three sequential bounces.', category: 'dots' },
  { id: '7', name: 'Double Bounce', variant: 'double-bounce', description: 'Overlapping circles.', category: 'dots' },
  { id: '8', name: 'Orbiting Dots', variant: 'dots-rotate', description: 'Orbital dot rotation.', category: 'dots' },
  { id: '9', name: 'Dots Chase', variant: 'dots-chase', description: 'Circular chase pattern.', category: 'dots' },
  { id: '10', name: 'Paired Revolution', variant: 'paired-revolution', description: 'Dual synchronized orbits.', category: 'dots' },
  { id: '11', name: 'Orbiting Spheres', variant: 'orbiting-spheres', description: '3D-depth orbiting dots.', category: 'dots' },
  { id: '12', name: 'Vertical Bars', variant: 'bars', description: 'Soundwave bar animation.', category: 'bars' },
  { id: '13', name: 'Audio Wave', variant: 'audio-wave', description: 'Audio waveform bars.', category: 'bars' },
  { id: '14', name: 'Matrix Grid', variant: 'grid', description: '3x3 pulsing grid.', category: 'bars' },
  { id: '15', name: 'Pulse Ring', variant: 'pulse-ring', description: 'Expanding ripple rings.', category: 'rings' },
  { id: '16', name: 'Concentric Rings', variant: 'concentric-rings', description: 'Nested ring pulses.', category: 'rings' },
  { id: '17', name: 'Ripple Pulse', variant: 'ripple-pulse', description: 'Water-like ripples.', category: 'rings' },
  { id: '18', name: 'Orbital Path', variant: 'orbit', description: 'Planetary orbit path.', category: 'rings' },
  { id: '19', name: 'Atomic Orbit', variant: 'atom', description: 'Electron cloud paths.', category: 'rings' },
  { id: '20', name: 'Radar Sweep', variant: 'radar-sweep', description: 'Rotating radar beam.', category: 'rings' },
  { id: '21', name: 'Ocean Wave', variant: 'wave-loader', description: 'Horizontal sine wave.', category: 'shapes' },
  { id: '22', name: 'Snake Tracer', variant: 'snake', description: 'Border trace animation.', category: 'shapes' },
  { id: '23', name: 'Infinity Loop', variant: 'infinity', description: 'Figure-eight path.', category: 'shapes' },
  { id: '24', name: 'Morphing Hexagon', variant: 'morphing-hex', description: 'Shape-shifting hexagon.', category: 'shapes' },
  { id: '25', name: 'Morphing Shape', variant: 'morphing-shape', description: 'Multi-form morph.', category: 'shapes' },
  { id: '26', name: 'Bloom Flower', variant: 'flower-spin', description: 'Breathing flower petals.', category: 'shapes' },
  { id: '27', name: 'Ethereal Glow', variant: 'glow-pulse', description: 'Soft blur pulse.', category: 'shapes' },
  { id: '28', name: 'Shimmer Card', variant: 'skeleton', description: 'Content placeholder sweep.', category: 'other' },
  { id: '29', name: 'Time Keeper', variant: 'clock', description: 'Rotating clock hands.', category: 'other' },
  { id: '30', name: 'Hourglass', variant: 'hourglass', description: 'Sand-timer flip.', category: 'other' },
  { id: '31', name: 'System Gear', variant: 'gear', description: 'Industrial gear rotation.', category: 'other' },
  { id: '32', name: 'Text Shimmer', variant: 'text-shimmer', description: 'Gradient text sweep.', category: 'other' },
  { id: '33', name: 'Vital Heartbeat', variant: 'heartbeat', description: 'Heartbeat pulse scale.', category: 'other' },
  { id: '34', name: 'Bio DNA', variant: 'loader-dna', description: 'Helix rotation.', category: 'other' },
  { id: '35', name: 'Digital Rain', variant: 'matrix', description: 'Falling data blocks.', category: 'other' },
  { id: '36', name: 'Floating Bubbles', variant: 'floating-bubble', description: 'Rising air bubbles.', category: 'other' },
  { id: '37', name: 'Eyes Gaze', variant: 'eyes-gaze', description: 'Looking eye animation.', category: 'other' },
  { id: '38', name: 'Ripple Wave', variant: 'ripple-wave', description: 'Wave-like ripple.', category: 'other' },
  { id: '39', name: 'Solar System', variant: 'solar-system', description: 'Planetary orbits.', category: 'other' },
  { id: '40', name: 'Coffee Steam', variant: 'coffee-cup', description: 'Rising cup steam.', category: 'other' },
  { id: '41', name: 'Progress Slide', variant: 'progress-slider', description: 'Sliding progress bar.', category: 'other' },
  { id: '42', name: 'Blocks Wave', variant: 'blocks-wave', description: 'Sequential block wave.', category: 'other' },
];
